In [1]:
import numpy as np

np.sort->return a sorted copy of an array.

In [2]:
# code
a=np.random.randint(1,100,15)
a

array([19, 51,  3,  2, 55, 89, 88, 68, 31, 63, 91, 69, 68, 91, 61],
      dtype=int32)

In [3]:
# ascending
np.sort(a)

array([ 2,  3, 19, 31, 51, 55, 61, 63, 68, 68, 69, 88, 89, 91, 91],
      dtype=int32)

In [4]:
# descending
np.sort(a)[::-1]

array([91, 91, 89, 88, 69, 68, 68, 63, 61, 55, 51, 31, 19,  3,  2],
      dtype=int32)

In [5]:
b=np.random.randint(1,100,24).reshape(6,4)
b

array([[51, 84, 20, 39],
       [94, 49, 26, 34],
       [96, 72, 39, 53],
       [92, 42, 72, 86],
       [ 7, 22, 92, 62],
       [82, 25, 78, 32]], dtype=int32)

In [6]:
np.sort(b,axis=0)

array([[ 7, 22, 20, 32],
       [51, 25, 26, 34],
       [82, 42, 39, 39],
       [92, 49, 72, 53],
       [94, 72, 78, 62],
       [96, 84, 92, 86]], dtype=int32)

np.append -> The numpy.append() appends value along the mentioned axis at the end of the array

In [7]:
np.append(a,200)

array([ 19,  51,   3,   2,  55,  89,  88,  68,  31,  63,  91,  69,  68,
        91,  61, 200])

In [8]:
np.append(b,np.ones((b.shape[0],1)),axis=1)

array([[51., 84., 20., 39.,  1.],
       [94., 49., 26., 34.,  1.],
       [96., 72., 39., 53.,  1.],
       [92., 42., 72., 86.,  1.],
       [ 7., 22., 92., 62.,  1.],
       [82., 25., 78., 32.,  1.]])

In [9]:
np.append(b,np.ones((1,b.shape[1])),axis=0)

array([[51., 84., 20., 39.],
       [94., 49., 26., 34.],
       [96., 72., 39., 53.],
       [92., 42., 72., 86.],
       [ 7., 22., 92., 62.],
       [82., 25., 78., 32.],
       [ 1.,  1.,  1.,  1.]])

np.concatenate -> This function concatenate a sequence of arrays along an existing axis.

In [10]:
c=np.arange(6).reshape(2,3)
d=np.arange(6,12).reshape(2,3)
print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [11]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

np.unique -> With the help of np.unique() method, we can get the unique values from an array given a parameter in np.unique() method.

In [12]:
e=np.array([1,1,2,3,2,2,4,5,6,4,3,6])

In [13]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

np.expand_dims -> With the help of numpy.expand_dims() method, we can get the expanded dimensions of an array

In [14]:
a

array([19, 51,  3,  2, 55, 89, 88, 68, 31, 63, 91, 69, 68, 91, 61],
      dtype=int32)

In [15]:
np.expand_dims(a,axis=1).shape

(15, 1)

In [16]:
np.expand_dims(a,axis=0).shape

(1, 15)

np.where -> The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

In [17]:
a

array([19, 51,  3,  2, 55, 89, 88, 68, 31, 63, 91, 69, 68, 91, 61],
      dtype=int32)

In [18]:
np.where(a>50)

(array([ 1,  4,  5,  6,  7,  9, 10, 11, 12, 13, 14]),)

In [19]:
# replace all values >50 with 0
np.where(a>50,0,a)

array([19,  0,  3,  2,  0,  0,  0,  0, 31,  0,  0,  0,  0,  0,  0],
      dtype=int32)

In [20]:
# replace all even value with 0
np.where(a%2==0,0,a)

array([19, 51,  3,  0, 55, 89,  0,  0, 31, 63, 91, 69,  0, 91, 61],
      dtype=int32)

np.argmax/np.argmin -> The numpy.argmax()/numpy.argmin() function returns indices of the max/min element of the array in a particular axis.

In [21]:
a

array([19, 51,  3,  2, 55, 89, 88, 68, 31, 63, 91, 69, 68, 91, 61],
      dtype=int32)

In [22]:
np.argmax(a)

np.int64(10)

In [23]:
b

array([[51, 84, 20, 39],
       [94, 49, 26, 34],
       [96, 72, 39, 53],
       [92, 42, 72, 86],
       [ 7, 22, 92, 62],
       [82, 25, 78, 32]], dtype=int32)

In [24]:
np.argmax(b,axis=0)

array([2, 0, 4, 3])

np.cumsum -> np.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

In [27]:
a

array([19, 51,  3,  2, 55, 89, 88, 68, 31, 63, 91, 69, 68, 91, 61],
      dtype=int32)

In [28]:
np.cumsum(a)

array([ 19,  70,  73,  75, 130, 219, 307, 375, 406, 469, 560, 629, 697,
       788, 849])

In [36]:
b

array([[51, 84, 20, 39],
       [94, 49, 26, 34],
       [96, 72, 39, 53],
       [92, 42, 72, 86],
       [ 7, 22, 92, 62],
       [82, 25, 78, 32]], dtype=int32)

In [37]:
np.cumsum(b,axis=0)

array([[ 51,  84,  20,  39],
       [145, 133,  46,  73],
       [241, 205,  85, 126],
       [333, 247, 157, 212],
       [340, 269, 249, 274],
       [422, 294, 327, 306]])

In [38]:
np.cumsum(b)

array([  51,  135,  155,  194,  288,  337,  363,  397,  493,  565,  604,
        657,  749,  791,  863,  949,  956,  978, 1070, 1132, 1214, 1239,
       1317, 1349])

np.percentile -> np.percentile() function used to compute the nth percentile of the given data (array elements) along the specified axis.

In [39]:
a

array([19, 51,  3,  2, 55, 89, 88, 68, 31, 63, 91, 69, 68, 91, 61],
      dtype=int32)

In [40]:
np.percentile(a,100)

np.float64(91.0)

In [42]:
np.percentile(a,50)

np.float64(63.0)

In [41]:
np.percentile(a,0)

np.float64(2.0)

n.histogram -> Numpy has a built-in np.histogram() function which represents the frequency of data distribution in the graphical form.

In [43]:
a

array([19, 51,  3,  2, 55, 89, 88, 68, 31, 63, 91, 69, 68, 91, 61],
      dtype=int32)

In [70]:
np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100])

(array([2, 1, 0, 1, 0, 2, 5, 0, 2, 2]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

np.corrcoef -> Return Pearson product-momoent correlation coefficients.

In [71]:
salary=np.array([20000,40000,25000,35000,60000])
experience=np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

np.isin -> With the help of np.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

In [73]:
a

array([19, 51,  3,  2, 55, 89, 88, 68, 31, 63, 91, 69, 68, 91, 61],
      dtype=int32)

In [80]:
items = [10,20,30,40,50,60,70,80,90,100]
np.isin(a,items)

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False])

np.flip -> The np.flip() function reverses the order of array elementd along the specified axis, preserving the shape of the array.

In [82]:
a

array([19, 51,  3,  2, 55, 89, 88, 68, 31, 63, 91, 69, 68, 91, 61],
      dtype=int32)

In [83]:
np.flip(a)

array([61, 91, 68, 69, 91, 63, 31, 68, 88, 89, 55,  2,  3, 51, 19],
      dtype=int32)

In [84]:
b

array([[51, 84, 20, 39],
       [94, 49, 26, 34],
       [96, 72, 39, 53],
       [92, 42, 72, 86],
       [ 7, 22, 92, 62],
       [82, 25, 78, 32]], dtype=int32)

In [86]:
np.flip(b,axis=0)

array([[82, 25, 78, 32],
       [ 7, 22, 92, 62],
       [92, 42, 72, 86],
       [96, 72, 39, 53],
       [94, 49, 26, 34],
       [51, 84, 20, 39]], dtype=int32)

In [89]:
g=np.arange(9).reshape(3,3)
g
np.flip(g)

array([[8, 7, 6],
       [5, 4, 3],
       [2, 1, 0]])

np.put -> The np.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array.

In [95]:
a

array([110, 110,   3,   2,  55,  89,  88,  68,  31,  63,  91,  69,  68,
        91,  61], dtype=int32)

In [94]:
np.put(a,[0,1],[110])