NUMPY ARRAY AND PYTHON LISTS

In [11]:
# speed
# list
a=[i for i in range(10000000)]
b=[i for i in range(10000000,20000000)]
c=[]
import time
start = time.time()
for i in range(len(a)):
    c.append(a[i] + b[i])
print(time.time()-start)

1.4706449508666992


In [7]:
# numpy
import numpy as np
a=np.arange(10000000)
b=np.arange(10000000,20000000)
start=time.time()
c=a+b
print(time.time()-start)

0.022388935089111328


In [13]:
1.47064/0.02238

65.71224307417336

In [18]:
# memory
a=[i for i in range(10000000)] 
import sys
sys.getsizeof(a)

89095160

In [16]:
a=np.arange(10000000,dtype=np.int32)
sys.getsizeof(a)

40000112

ADVANCED INDEXING

In [28]:
# Normal Indexing and slicing
a=np.arange(24).reshape(6,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
# index
a[3,2]
# slicing
a[1:3,1:3]

np.int64(11)

In [34]:
# Fancy Indexing
a[[0,2,3,5]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [20, 21, 22, 23]])

In [35]:
a[:,[0,2,3]]

array([[ 0,  2,  3],
       [ 4,  6,  7],
       [ 8, 10, 11],
       [12, 14, 15],
       [16, 18, 19],
       [20, 22, 23]])

In [48]:
# Boolean Indexing
a=np.random.randint(1,100,24).reshape(6,4)
a

array([[23,  6, 13, 42],
       [63, 85, 35, 42],
       [50, 84, 21, 86],
       [55, 72, 73, 31],
       [22, 21,  1, 80],
       [41, 95, 91, 96]], dtype=int32)

In [54]:
# Find all numbers greater than 50
a[a>50]

array([63, 85, 84, 86, 55, 72, 73, 80, 95, 91, 96], dtype=int32)

In [56]:
# Find the even number
a[a%2==0]

array([ 6, 42, 42, 50, 84, 86, 72, 22, 80, 96], dtype=int32)

In [64]:
# Find all numbers greater than 50 and are even
a[(a>50) & (a%2==0)]

array([84, 86, 72, 80, 96], dtype=int32)

In [ ]:
# Find all numbers not divisible by 7
a[a%7!=0] # a[~(a%7==0)]

array([23,  6, 13, 85, 50, 86, 55, 72, 73, 31, 22,  1, 80, 41, 95, 96],
      dtype=int32)

BROADCASTING

In [ ]:
a=np.arange(6).reshape(2,3)
b=np.arange(3).reshape(1,3)
print(a)
print(b)
a+b # This is possible because of broadcasting

[[0 1 2]
 [3 4 5]]
[[0 1 2]]


array([[0, 2, 4],
       [3, 5, 7]])

In [67]:
# More Example
a=np.arange(12).reshape(4,3)
b=np.arange(3)
print(a)
print(b)
a+b

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[0 1 2]


array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10],
       [ 9, 11, 13]])

In [68]:
a=np.arange(12).reshape(3,4)
b=np.arange(3)
print(a)
print(b)
a+b

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[0 1 2]


ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [69]:
a=np.arange(3).reshape(1,3)
b=np.arange(3).reshape(3,1)
a+b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [74]:
a=np.arange(1,2)
b=np.arange(4).reshape(2,2)
print(a)
print(b)
print(a+b)


[1]
[[0 1]
 [2 3]]
[[1 2]
 [3 4]]


In [75]:
a=np.arange(12).reshape(3,4)
b=np.arange(12).reshape(4,3)
a+b

ValueError: operands could not be broadcast together with shapes (3,4) (4,3) 

In [77]:
a=np.arange(16).reshape(4,4)
b=np.arange(4).reshape(2,2)
a+b

ValueError: operands could not be broadcast together with shapes (4,4) (2,2) 

WORKING WITH MATHEMATICAL FORMULAS

In [81]:
# Sigmoid
def sigmoid(array):
    return 1/(1+np.exp(-(array)))
a=np.arange(10)
sigmoid(a)


array([0.5       , 0.73105858, 0.88079708, 0.95257413, 0.98201379,
       0.99330715, 0.99752738, 0.99908895, 0.99966465, 0.99987661])

In [101]:
# Mean squared error
actual = np.random.randint(1,50,25)
predicted = np.random.randint(1,50,25)

In [102]:
def mse(actual,predicted):
    return np.mean((actual-predicted)**2)

mse(actual, predicted)

np.float64(450.32)

In [103]:
# Binary cross entropy
