In [2]:
import numpy as np

np.sort->return a sorted copy of an array.

In [3]:
# code
a=np.random.randint(1,100,15)
a

array([63, 12, 66, 34, 43, 72, 48, 53,  4,  1, 10, 23, 92, 50, 78],
      dtype=int32)

In [4]:
# ascending
np.sort(a)

array([ 1,  4, 10, 12, 23, 34, 43, 48, 50, 53, 63, 66, 72, 78, 92],
      dtype=int32)

In [5]:
# descending
np.sort(a)[::-1]

array([92, 78, 72, 66, 63, 53, 50, 48, 43, 34, 23, 12, 10,  4,  1],
      dtype=int32)

In [6]:
b=np.random.randint(1,100,24).reshape(6,4)
b

array([[12, 28, 51, 31],
       [92, 52,  2,  9],
       [47, 58, 76, 85],
       [27, 30, 31, 63],
       [93, 72, 85, 94],
       [84, 28, 51, 73]], dtype=int32)

In [7]:
np.sort(b,axis=0)

array([[12, 28,  2,  9],
       [27, 28, 31, 31],
       [47, 30, 51, 63],
       [84, 52, 51, 73],
       [92, 58, 76, 85],
       [93, 72, 85, 94]], dtype=int32)

np.append -> The numpy.append() appends value along the mentioned axis at the end of the array

In [8]:
np.append(a,200)

array([ 63,  12,  66,  34,  43,  72,  48,  53,   4,   1,  10,  23,  92,
        50,  78, 200])

In [9]:
np.append(b,np.ones((b.shape[0],1)),axis=1)

array([[12., 28., 51., 31.,  1.],
       [92., 52.,  2.,  9.,  1.],
       [47., 58., 76., 85.,  1.],
       [27., 30., 31., 63.,  1.],
       [93., 72., 85., 94.,  1.],
       [84., 28., 51., 73.,  1.]])

In [10]:
np.append(b,np.ones((1,b.shape[1])),axis=0)

array([[12., 28., 51., 31.],
       [92., 52.,  2.,  9.],
       [47., 58., 76., 85.],
       [27., 30., 31., 63.],
       [93., 72., 85., 94.],
       [84., 28., 51., 73.],
       [ 1.,  1.,  1.,  1.]])

np.concatenate -> This function concatenate a sequence of arrays along an existing axis.

In [11]:
c=np.arange(6).reshape(2,3)
d=np.arange(6,12).reshape(2,3)
print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [12]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

np.unique -> With the help of np.unique() method, we can get the unique values from an array given a parameter in np.unique() method.

In [13]:
e=np.array([1,1,2,3,2,2,4,5,6,4,3,6])

In [14]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

np.expand_dims -> With the help of numpy.expand_dims() method, we can get the expanded dimensions of an array

In [15]:
a

array([63, 12, 66, 34, 43, 72, 48, 53,  4,  1, 10, 23, 92, 50, 78],
      dtype=int32)

In [16]:
np.expand_dims(a,axis=1).shape

(15, 1)

In [17]:
np.expand_dims(a,axis=0).shape

(1, 15)

np.where -> The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

In [18]:
a

array([63, 12, 66, 34, 43, 72, 48, 53,  4,  1, 10, 23, 92, 50, 78],
      dtype=int32)

In [19]:
np.where(a>50)

(array([ 0,  2,  5,  7, 12, 14]),)

In [20]:
# replace all values >50 with 0
np.where(a>50,0,a)

array([ 0, 12,  0, 34, 43,  0, 48,  0,  4,  1, 10, 23,  0, 50,  0],
      dtype=int32)

In [21]:
# replace all even value with 0
np.where(a%2==0,0,a)

array([63,  0,  0,  0, 43,  0,  0, 53,  0,  1,  0, 23,  0,  0,  0],
      dtype=int32)

np.argmax/np.argmin -> The numpy.argmax()/numpy.argmin() function returns indices of the max/min element of the array in a particular axis.

In [22]:
a

array([63, 12, 66, 34, 43, 72, 48, 53,  4,  1, 10, 23, 92, 50, 78],
      dtype=int32)

In [23]:
np.argmax(a)

np.int64(12)

In [24]:
b

array([[12, 28, 51, 31],
       [92, 52,  2,  9],
       [47, 58, 76, 85],
       [27, 30, 31, 63],
       [93, 72, 85, 94],
       [84, 28, 51, 73]], dtype=int32)

In [25]:
np.argmax(b,axis=0)

array([4, 4, 4, 4])

np.cumsum -> np.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

In [26]:
a

array([63, 12, 66, 34, 43, 72, 48, 53,  4,  1, 10, 23, 92, 50, 78],
      dtype=int32)

In [27]:
np.cumsum(a)

array([ 63,  75, 141, 175, 218, 290, 338, 391, 395, 396, 406, 429, 521,
       571, 649])

In [28]:
b

array([[12, 28, 51, 31],
       [92, 52,  2,  9],
       [47, 58, 76, 85],
       [27, 30, 31, 63],
       [93, 72, 85, 94],
       [84, 28, 51, 73]], dtype=int32)

In [29]:
np.cumsum(b,axis=0)

array([[ 12,  28,  51,  31],
       [104,  80,  53,  40],
       [151, 138, 129, 125],
       [178, 168, 160, 188],
       [271, 240, 245, 282],
       [355, 268, 296, 355]])

In [30]:
np.cumsum(b)

array([  12,   40,   91,  122,  214,  266,  268,  277,  324,  382,  458,
        543,  570,  600,  631,  694,  787,  859,  944, 1038, 1122, 1150,
       1201, 1274])

np.percentile -> np.percentile() function used to compute the nth percentile of the given data (array elements) along the specified axis.

In [31]:
a

array([63, 12, 66, 34, 43, 72, 48, 53,  4,  1, 10, 23, 92, 50, 78],
      dtype=int32)

In [32]:
np.percentile(a,100)

np.float64(92.0)

In [33]:
np.percentile(a,50)

np.float64(48.0)

In [34]:
np.percentile(a,0)

np.float64(1.0)

n.histogram -> Numpy has a built-in np.histogram() function which represents the frequency of data distribution in the graphical form.

In [35]:
a

array([63, 12, 66, 34, 43, 72, 48, 53,  4,  1, 10, 23, 92, 50, 78],
      dtype=int32)

In [36]:
np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100])

(array([2, 2, 1, 1, 2, 2, 2, 2, 0, 1]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

np.corrcoef -> Return Pearson product-momoent correlation coefficients.

In [37]:
salary=np.array([20000,40000,25000,35000,60000])
experience=np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

np.isin -> With the help of np.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

In [38]:
a

array([63, 12, 66, 34, 43, 72, 48, 53,  4,  1, 10, 23, 92, 50, 78],
      dtype=int32)

In [39]:
items = [10,20,30,40,50,60,70,80,90,100]
np.isin(a,items)

array([False, False, False, False, False, False, False, False, False,
       False,  True, False, False,  True, False])

np.flip -> The np.flip() function reverses the order of array elementd along the specified axis, preserving the shape of the array.

In [40]:
a

array([63, 12, 66, 34, 43, 72, 48, 53,  4,  1, 10, 23, 92, 50, 78],
      dtype=int32)

In [41]:
np.flip(a)

array([78, 50, 92, 23, 10,  1,  4, 53, 48, 72, 43, 34, 66, 12, 63],
      dtype=int32)

In [42]:
b

array([[12, 28, 51, 31],
       [92, 52,  2,  9],
       [47, 58, 76, 85],
       [27, 30, 31, 63],
       [93, 72, 85, 94],
       [84, 28, 51, 73]], dtype=int32)

In [43]:
np.flip(b,axis=0)

array([[84, 28, 51, 73],
       [93, 72, 85, 94],
       [27, 30, 31, 63],
       [47, 58, 76, 85],
       [92, 52,  2,  9],
       [12, 28, 51, 31]], dtype=int32)

In [44]:
g=np.arange(9).reshape(3,3)
g
np.flip(g)

array([[8, 7, 6],
       [5, 4, 3],
       [2, 1, 0]])

np.put -> The np.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array.

In [45]:
a

array([63, 12, 66, 34, 43, 72, 48, 53,  4,  1, 10, 23, 92, 50, 78],
      dtype=int32)

In [46]:
np.put(a,[0,1],[110])

np.delete -> It returns a new array with the deletion of sub-arrays along with the mentioned axis.

In [47]:
a

array([110, 110,  66,  34,  43,  72,  48,  53,   4,   1,  10,  23,  92,
        50,  78], dtype=int32)

In [48]:
np.delete(a,[0,2,5])

array([110,  34,  43,  48,  53,   4,   1,  10,  23,  92,  50,  78],
      dtype=int32)

Set functions
-np.union1d
-np.intersect1d
-np.setdiff1d
-np.setxor1d
-np.in1d

In [49]:
m=np.array([1,2,3,4,5])
n=np.array([3,4,5,6,7])

In [50]:
np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [51]:
np.intersect1d(m,n)

array([3, 4, 5])

In [52]:
np.setdiff1d(m,n)

array([1, 2])

In [53]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [54]:
np.in1d(m,1)

C:\Users\sudha\AppData\Local\Temp\ipykernel_40260\3930963099.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  np.in1d(m,1)


array([ True, False, False, False, False])

np.clip -> np.clip() function is used to clip (limit) the values in an array.

In [55]:
a

array([110, 110,  66,  34,  43,  72,  48,  53,   4,   1,  10,  23,  92,
        50,  78], dtype=int32)

In [56]:
np.clip(a,a_min=25, a_max=75)

array([75, 75, 66, 34, 43, 72, 48, 53, 25, 25, 25, 25, 75, 50, 75],
      dtype=int32)

In [58]:
a=int(input("Enter the value of a:"))
b=int(input("Enter the value of b:"))
c=np.random.randint(1,100,a*b).reshape(a,b)
print(c)
print(np.mean(c))

[[23 56]
 [71 74]
 [85 62]]
61.833333333333336
