CREATING NUMPY ARRAY

In [81]:
import numpy as np

a=np.array([1,2,3])
print(a)

[1 2 3]


In [82]:
# 2D and 3D
b=np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [83]:
c=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [84]:
# dtype
np.array([1,2,3],dtype=float)


array([1., 2., 3.])

In [85]:
# np.arange
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [86]:
# with reshape
np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [87]:
# np.ones and np.zeros
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [88]:
# np.random
np.random.random((2,3))

array([[0.43633388, 0.89873614, 0.26624666],
       [0.57899851, 0.69977046, 0.43034349]])

In [89]:
# np.linspace
np.linspace(-10,10,5)

array([-10.,  -5.,   0.,   5.,  10.])

ARRAY ATTRIBUTES

In [90]:
a1=np.arange(10)
a2=np.arange(12,dtype=float).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)
print(a1)
print(a2)
print(a3)

[0 1 2 3 4 5 6 7 8 9]
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [91]:
# ndim
a3.ndim

3

In [92]:
# shape
print(a3.shape)
a3

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [93]:
# size
a2.size

12

In [94]:
# itemsize
a1.itemsize

8

In [95]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int64
float64
int64


CHANGING DATATYPE

In [96]:
# astype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

ARRAY OPERATIONS

In [97]:
a1=np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(3,4)

In [98]:
# SCALAR OPERATIONS
# Arithmatice 
print(a1+4)
print(a1*2)

[[ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]


In [99]:
# Relational
a2==15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [100]:
# VECTOR OPERATION
# Arithmatic
a1+a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

ARRAY FUNCTIONS

In [101]:
a1=np.random.random((3,3))
a1=np.round(a1*100)
a1

array([[25.,  1., 33.],
       [83., 98., 38.],
       [42.,  8., 61.]])

In [102]:
# max/min/sum/product
print(np.max(a1))
print(np.min(a1))
print(np.sum(a1))
print(np.prod(a1))

98.0
1.0
389.0
5226498446400.0


In [103]:
# mean/median/std/var
print(np.mean(a1))
print(np.median(a1))
print(np.std(a1))
print(np.var(a1))

43.22222222222222
38.0
30.52786624191004
931.9506172839506


In [104]:
# Trignometric Functions
np.sin(a1)

array([[-0.13235175,  0.84147098,  0.99991186],
       [ 0.96836446, -0.57338187,  0.29636858],
       [-0.91652155,  0.98935825, -0.96611777]])

In [105]:
# Dot Product
a2=np.arange(12).reshape(3,4)
a3=np.arange(12,24).reshape(4,3)
print(a2)
print(a3)
print(np.dot(a2,a3))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
[[114 120 126]
 [378 400 422]
 [642 680 718]]


INDEXING AND SLICING

INDEXING

In [106]:
a1=np.arange(10)
a2=np.arange(12).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)

In [113]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [114]:
a1[0]

np.int64(0)

In [115]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [112]:
a2[1,2]

np.int64(6)

In [116]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [120]:
a3[1,1,0]

np.int64(6)

SLICING

1D ARRAY SLICING

In [121]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [123]:
a1[1:3]

array([1, 2])

2D ARRAY SLICING

In [124]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [127]:
a2[0,:]

array([0, 1, 2, 3])

In [128]:
a2[:,2]

array([ 2,  6, 10])

In [134]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [145]:
a2[0::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [147]:
a2[0::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [155]:
a2[1,::3]

array([4, 7])

In [162]:
a2[0:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

3D ARRAY SLICING

In [163]:
a3=np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [165]:
a3[1,0:]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [169]:
a3[0::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [170]:
a3[0,1]

array([3, 4, 5])

In [171]:
a3[1,:,1]

array([10, 13, 16])

In [172]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [173]:
a3[0::2,0,::2]

array([[ 0,  2],
       [18, 20]])

ITERATING

In [177]:
a1
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [178]:
a2
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [182]:
a3
for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [183]:
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


RESHAPING

In [ ]:
# reshape
a1=np.arange(10)
a2=a1.reshape(2,5)
a2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [205]:
# Transpose
np.transpose(a2) 
# or can use
a3.T

array([[[ 0,  9, 18],
        [ 3, 12, 21],
        [ 6, 15, 24]],

       [[ 1, 10, 19],
        [ 4, 13, 22],
        [ 7, 16, 25]],

       [[ 2, 11, 20],
        [ 5, 14, 23],
        [ 8, 17, 26]]])

In [211]:
# Ravel
a2.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Stacking

In [213]:
a4=np.arange(12).reshape(3,4)
a5=np.arange(12,24).reshape(3,4)

In [214]:
# Horizontal stacking
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [216]:
# Vertical stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

Splitting

In [219]:
# Horizontal splitting
print(a4)
np.hsplit(a4,2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [230]:
# Vertical splitting
print(a4)
np.vsplit(a5,3)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]